/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */
package com.pingplusplus.android;

public final class R {
	public static final class color {
		public static final int fqlpay_wap_color = 0x7f060000;
		public static final int mmdpay_wap_color = 0x7f060002;
		public static final int qgbc_wap_color = 0x7f060003;
	}
	public static final class dimen {
		public static final int activity_horizontal_margin = 0x7f0503e8;
		public static final int activity_vertical_margin = 0x7f0503e9;
	}
	public static final class drawable {
		public static final int pingpp_back = 0x7f020001;
		public static final int tips_bg = 0x7f020013;
	}
	public static final class id {
		public static final int pingpp_back = 0x7f090001;
		public static final int pingpp_progressbar = 0x7f090003;
		public static final int pingpp_title = 0x7f090000;
		public static final int pingpp_webView = 0x7f090002;
	}
	public static final class layout {
		public static final int activity_pingpp_payment = 0x7f030000;
	}
	public static final class style {
		public static final int AppBaseTheme = 0x7f080000;
		public static final int AppTheme = 0x7f080001;
	}
}
